# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kaydet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setWindowTitle(object):
    def setupUi(self, setWindowTitle):
        setWindowTitle.setObjectName("setWindowTitle")
        setWindowTitle.resize(800, 828)
        self.centralwidget = QtWidgets.QWidget(setWindowTitle)
        self.centralwidget.setObjectName("centralwidget")
        self.kaydet_button = QtWidgets.QPushButton(self.centralwidget)
        self.kaydet_button.setGeometry(QtCore.QRect(270, 620, 75, 23))
        self.kaydet_button.setObjectName("kaydet_button")
        self.tckimlik_input = QtWidgets.QLineEdit(self.centralwidget)
        self.tckimlik_input.setGeometry(QtCore.QRect(260, 140, 131, 31))
        self.tckimlik_input.setObjectName("tckimlik_input")
        self.ad_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_input.setGeometry(QtCore.QRect(260, 210, 131, 31))
        self.ad_input.setObjectName("ad_input")
        self.soyad_input = QtWidgets.QLineEdit(self.centralwidget)
        self.soyad_input.setGeometry(QtCore.QRect(260, 270, 131, 31))
        self.soyad_input.setObjectName("soyad_input")
        self.dogum_calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.dogum_calendar.setGeometry(QtCore.QRect(260, 340, 256, 190))
        self.dogum_calendar.setObjectName("dogum_calendar")
        self.erkek_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.erkek_radio.setGeometry(QtCore.QRect(270, 570, 74, 18))
        self.erkek_radio.setObjectName("erkek_radio")
        self.kadin_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.kadin_radio.setGeometry(QtCore.QRect(330, 570, 74, 18))
        self.kadin_radio.setObjectName("kadin_radio")
        self.cinsiyet_label = QtWidgets.QLabel(self.centralwidget)
        self.cinsiyet_label.setGeometry(QtCore.QRect(190, 570, 47, 14))
        self.cinsiyet_label.setObjectName("cinsiyet_label")
        self.tckimlik_label = QtWidgets.QLabel(self.centralwidget)
        self.tckimlik_label.setGeometry(QtCore.QRect(180, 140, 47, 14))
        self.tckimlik_label.setObjectName("tckimlik_label")
        self.ad_label = QtWidgets.QLabel(self.centralwidget)
        self.ad_label.setGeometry(QtCore.QRect(180, 210, 47, 14))
        self.ad_label.setObjectName("ad_label")
        self.soyad_label = QtWidgets.QLabel(self.centralwidget)
        self.soyad_label.setGeometry(QtCore.QRect(180, 270, 47, 14))
        self.soyad_label.setObjectName("soyad_label")
        self.dogum_label = QtWidgets.QLabel(self.centralwidget)
        self.dogum_label.setGeometry(QtCore.QRect(170, 340, 91, 31))
        self.dogum_label.setObjectName("dogum_label")
        self.mesaj_label = QtWidgets.QLabel(self.centralwidget)
        self.mesaj_label.setGeometry(QtCore.QRect(270, 670, 147, 140))
        self.mesaj_label.setText("")
        self.mesaj_label.setObjectName("mesaj_label")
        setWindowTitle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(setWindowTitle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        setWindowTitle.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(setWindowTitle)
        self.statusbar.setObjectName("statusbar")
        setWindowTitle.setStatusBar(self.statusbar)

        self.retranslateUi(setWindowTitle)
        QtCore.QMetaObject.connectSlotsByName(setWindowTitle)

    def retranslateUi(self, setWindowTitle):
        _translate = QtCore.QCoreApplication.translate
        setWindowTitle.setWindowTitle(_translate("setWindowTitle", "MainWindow"))
        self.kaydet_button.setText(_translate("setWindowTitle", "KAYDET"))
        self.erkek_radio.setText(_translate("setWindowTitle", "ERKEK"))
        self.kadin_radio.setText(_translate("setWindowTitle", "KADIN"))
        self.cinsiyet_label.setText(_translate("setWindowTitle", "Cinsiyet"))
        self.tckimlik_label.setText(_translate("setWindowTitle", "TC Kimlik"))
        self.ad_label.setText(_translate("setWindowTitle", "Ad :"))
        self.soyad_label.setText(_translate("setWindowTitle", "Soyad :"))
        self.dogum_label.setText(_translate("setWindowTitle", "Doğum Tarihi :"))
